### PR TITLE
Add Handdrawing Notebook example

### PR DESCRIPTION
**Pull request by martinRenou**
+ Add default values for `draw_image` arguments

### CODE REVIEW

**Comment by stonebig** [comment]
argh, still not on binder

**Comment by martinRenou** [comment]
Coming soon! I'm making a release right now :) (the binder link is pointing to the `stable` branch, not `master`). Once the package is on conda I will update the `stable` branch. It might take an hour.

**Comment by martinRenou** [comment]
@stonebig you can run it locally anyway ;) installing ipycanvas 0.4.0 with pip

**Comment by martinRenou** [comment]
@stonebig It's on binder now :)

**Pull request merged**
