### PR TITLE
Add 3D plot example

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by martinRenou** [comment]
Impressive demo! Thanks! I'll try to get the 3D projection without matplotlib :)

**Comment by fschiffers** [comment]
Hello,

the zooming works for me, however, the 3D rotation doesn't work. I think the mouse events are not captured.

I'm starting the kernel remotely on an Ubuntu system and I'm opening the Jupyter Lab on a MacOS system. The drag-and-drop example works fine though.

Do you have any ideas what could go wrong?

**Comment by davidbrochart** [comment]
You are right, it doesn't work anymore with the latest version. I'll try and see what's wrong.

**Comment by davidbrochart** [comment]
I fixed it by using a `Canvas` instead of a `MultiCanvas`. Maybe @martinRenou knows why it doesn't work with a `MultiCanvas` anymore?

**Comment by fschiffers** [comment]
Thanks David! This works great :)

**Comment by dsblank** [comment]
@davidbrochart This PR works great, and looks good to me. One question: what does the `out` in the final cell supposed to do? I only get a horizontal line (I presume the border on a zero height canvas):

Screenshot from 2020-12-12 07-49-46

**Comment by davidbrochart** [comment]
`out` is an `Output` widget that I used to print debug messages, you can remove it.
I think @martinRenou didn't want to depend on matplotlib for this example, so one improvement would be to compute the 3D stuff in pure Python. Do you want to give it a try?

**Comment by dsblank** [comment]
@davidbrochart thanks for the info. No, I don't think it is worth it to re-write parts of matplotlib here just to avoid the dependency.

I guess you could add a cell at the beginning to install it, and remove it from the dependencies:

```
%pip install matplotlib
```

**Comment by martinRenou** [comment]
Well, matplotlib is used here for making a 3D projection matrix, NumPy is far from enough when it comes to matrix multiplications.

I'll find time this week to update this PR. I'd like to get this in before the next release.

**Comment by martinRenou** [comment]
Done @davidbrochart, would you mind reviewing my changes? :)

**Comment by davidbrochart** [comment]
Awesome!
I trust you on the 3D computation stuff, but there are some differences with [my original PR](https://mybinder.org/v2/gh/davidbrochart/ipycanvas/plot3d?filepath=examples/plot3d.ipynb). [In yours](https://mybinder.org/v2/gh/martinrenou/ipycanvas/plot3d?filepath=examples/plot3d.ipynb), it doesn't seem to be possible to zoom anymore, and the points are not centered in the canvas.

**Comment by martinRenou** [comment]
> but there are some differences with my original PR. In yours

I am pushing to your branch, so the link you pointed to with "[my original PR](https://mybinder.org/v2/gh/davidbrochart/ipycanvas/plot3d?filepath=examples/plot3d.ipynb)" is actually my code :) The other link is out of date, it was me pushing to my fork a half working Notebook by mistake.

**Comment by davidbrochart** [comment]
Oh, that's right. Then it's all fine!

**Comment by davidbrochart** [comment]
Maybe one thing, I thought the points were getting bigger as you zoomed in, but I'm not sure anymore.

**Comment by davidbrochart** [comment]
And maybe the slider should be inverted: it should zoom in when sliding to the right?

**Comment by martinRenou** [comment]
Indeed, but the way you were doing it was not correct IMO. We should compute the right size depending on the distance view/point, we have this information in the third result of the projection, I'll figure this out.

**Comment by martinRenou** [comment]
> And maybe the slider should be inverted: it should zoom in when sliding to the right?

It's less of a zoom than it is the orbit control radius now, I should maybe rename the `on_zoom` function, and make it clear that it's the camera position that's moving

**Comment by martinRenou** [comment]
> Maybe one thing, I thought the points were getting bigger as you zoomed in, but I'm not sure anymore.

I came up with something, not sure it's mathematically correct, I am braindead after this day of work :P Anyway, it seems to do the trick.

**Pull request merged**
