### PR TITLE
Add mapping application

### PR DESCRIPTION
**Pull request by davidbrochart**
This is a simple mapping example which uses OSM tiles.

### CODE REVIEW

**Comment by martinRenou** [comment]
That is a super nice example! :)

**Comment by martinRenou** [comment]
Tell me if that is ready to merged :) I'm happy to merge it as it is

**Comment by davidbrochart** [comment]
Yes, we can merge it as is and improve it in the future.

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
